
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON Proveedor TO administrador;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON Tipo TO administrador;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON Color TO administrador;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON Zapato TO administrador;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON Stock TO administrador;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON Persona TO administrador;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON Metodo_Pago TO administrador;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON Compra TO administrador;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE, DELETE ON Carrito_Compra TO administrador;
GO
USE KOALASA;
GO

USE KOALASA
GO
GRANT SELECT, INSERT, UPDATE ON Proveedor TO vendedor;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE ON Tipo TO vendedor;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE ON Color TO vendedor;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE ON Zapato TO vendedor;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE ON Stock TO vendedor;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE ON Persona TO vendedor;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE ON Metodo_Pago TO vendedor;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE ON Compra TO vendedor;
GO
USE KOALASA;
GO
GRANT SELECT, INSERT, UPDATE ON Carrito_Compra TO vendedor;
GO
USE KOALASA;
GO

USE KOALASA
GO
GRANT SELECT ON Tipo TO cliente;
GO
USE KOALASA;
GO
GRANT SELECT ON Proveedor TO cliente;
GO
USE KOALASA;
GO
GRANT SELECT ON Color TO cliente;
GO
USE KOALASA;
GO
GRANT SELECT ON Zapato TO cliente;
GO
USE KOALASA;
GO
GRANT SELECT ON Stock TO cliente;
GO
USE KOALASA;
GO
GRANT SELECT ON Persona TO cliente;
GO
USE KOALASA;
GO
GRANT SELECT ON Metodo_Pago TO cliente;
GO
USE KOALASA;
GO
GRANT SELECT ON Compra TO cliente;
GO
USE KOALASA;
GO
GRANT SELECT ON Carrito_Compra TO cliente;
GO
USE KOALASA;
GO






