
--Parte 11 Seguridad, Permisos Para Cada tipo de usuario
USE KOALASA
GO
GRANT EXECUTE ON SP_INGRESAR_TIPO TO Vendedor;
GRANT EXECUTE ON SP_INGRESAR_COLOR TO Vendedor;
GRANT EXECUTE ON SP_INGRESAR_ZAPATO TO Vendedor;
GRANT EXECUTE ON SP_INGRESAR_ZAPATO_POR_NOMBRE TO Vendedor;
GRANT EXECUTE ON SP_INGRESAR_PERSONA TO Vendedor;
GRANT EXECUTE ON SP_INGRESAR_ARTICULO_A_CARRITO TO Vendedor;
GRANT EXECUTE ON SP_GENERAR_COMPRA TO Vendedor;
GRANT EXECUTE ON SP_COMPRA_COMO_VENDEDOR TO Vendedor;
GRANT EXECUTE ON SP_CATALO_DE_ZAPATOS TO Vendedor;
GRANT EXECUTE ON SP_CATALO_DE_ZAPATOS_POR_GENERO TO Vendedor;
GRANT EXECUTE ON SP_VENTAS_POR_CODIGO_ZAPATO TO Vendedor;
GRANT EXECUTE ON SP_VENTAS_POR_ZAPATO TO Vendedor;
GRANT EXECUTE ON SP_ARTICULOS_COMPRA_POR_CEDULA_CLIENTE TO Vendedor;
GRANT EXECUTE ON SP_COMPRA_POR_CEDULA_CLIENTE TO Vendedor;
GRANT EXECUTE ON SP_ARTICULOS_COMPRA_POR_NUMFACTURA TO Vendedor;
GRANT EXECUTE ON SP_COMPRA_POR_NUMFACTURA TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_APELLIDOS_PERSONA TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_CANTIDAD_CARRITO TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_CLIENTE_COMPRA TO Vendedor;
GRANT EXECUTE ON SP_BUSCAR_RANGO_PRECIO TO Vendedor;
GRANT EXECUTE ON SP_BUSCAR_RANGO_TALLAS TO Vendedor;
GRANT EXECUTE ON SP_BUSCAR_STOCK_MAYOR_A TO Vendedor;
GRANT EXECUTE ON SP_BUSCAR_STOCK_MENOR_A TO Vendedor;
GRANT EXECUTE ON SP_BUSCAR_TALLA TO Vendedor;
GRANT EXECUTE ON SP_BUSCAR_ZAPATO_POR_CODIGO TO Vendedor;
GRANT EXECUTE ON SP_BuscarProveedor_CedulaJ TO Vendedor;
GRANT EXECUTE ON SP_BUSCAR_PERSONA_APELLIDO TO Vendedor;
GRANT EXECUTE ON SP_BUSCAR_PERSONA_CEDULA TO Vendedor;
GRANT EXECUTE ON SP_BUSCAR_PERSONA_NOMBRE TO Vendedor;
GRANT EXECUTE ON SP_BUSCAR_ZAPATO_POR_PROVEEDOR TO Vendedor;
GRANT EXECUTE ON SP_BuscarProveedor_Codigo TO Vendedor;
GRANT EXECUTE ON SP_BuscarProveedor_Estado TO Vendedor;
GRANT EXECUTE ON SP_BuscarProveedor_Nombre TO Vendedor;
GRANT EXECUTE ON Sp_BuscarTiposPorProveedor TO Vendedor;
GRANT EXECUTE ON SP_BuscarZapato_POR_Color TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_CORREO_PERSONA TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_DIRECCION_PERSONA TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_EXISTENCIAS_STOCK TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_FECHA_COMPRA TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_METODO_PAGO_COMPRA TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_NOMBRE_PERSONA TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_SUBTOTAL_CARRITO TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_TALLA_ZAPATO TO Vendedor;
GRANT EXECUTE ON SP_EDITAR_TELEFONO_PERSONA TO Vendedor;
GRANT EXECUTE ON SP_INFO_VENTAS_DEL_MES TO Vendedor;
GRANT EXECUTE ON SP_VENTAS_EN_EL_MES TO Vendedor;
GO

USE KOALASA
GO
GRANT EXECUTE ON SP_COMPRA_POR_NUMFACTURA TO Cliente;
GRANT EXECUTE ON SP_ARTICULOS_COMPRA_POR_NUMFACTURA TO Cliente;
GRANT EXECUTE ON SP_ARTICULOS_COMPRA_POR_CEDULA_CLIENTE TO Cliente;
GRANT EXECUTE ON SP_COMPRA_POR_CEDULA_CLIENTE TO Cliente;
GRANT EXECUTE ON SP_CATALO_DE_ZAPATOS TO Cliente;
GRANT EXECUTE ON SP_CATALO_DE_ZAPATOS_POR_GENERO TO Cliente;
GO