--Parte 13 Executes 

USE KOALASA
GO
EXECUTE AS USER = 'KOALAADMIN';
GO
EXEC SP_INGRESAR_PROVEEDOR 'P-0115', 'KangarooKrafts', '12131436', '+506 66213477', 'KangarooKrafts@empresa.com';
GO
EXEC SP_INGRESAR_PROVEEDOR 'P-0116', 'PantherProducts', '12131427', '+506 66213468', 'PantherProducts@empresa.com';
GO
EXEC SP_INGRESAR_PROVEEDOR 'P-0197', 'HyenaHoldings', '12131428', '+506 66213469', 'HyenaHoldings@empresa.com';
GO
EXEC SP_INGRESAR_COLOR 'AZUL';
GO
EXEC SP_INGRESAR_COLOR 'VERDE';
GO
EXEC SP_INGRESAR_COLOR 'NEGRO';
GO
EXEC SP_INGRESAR_TIPO 'INVIERNO', 'P-0115','U';
GO
EXEC SP_INGRESAR_TIPO 'VERANO', 'P-0116','M';
GO
EXEC SP_INGRESAR_TIPO 'PUNK', 'P-0197','H';
GO
EXECUTE SP_INGRESAR_ZAPATO_POR_NOMBRE 'Punk','Negro',41,$35,50
GO
EXECUTE SP_INGRESAR_ZAPATO_POR_NOMBRE 'VERANO','AZUL',41,$80,50
GO
EXECUTE SP_INGRESAR_ZAPATO_POR_NOMBRE 'INVIERNO','AZUL',41,$135,2
GO
REVERT;
GO

USE KOALASA
Go
EXEC SP_AñADIR_METODO_PAGO 'Apple Pay';
GO
EXEC SP_AñADIR_METODO_PAGO 'Google Pay';
GO
EXEC SP_AñADIR_METODO_PAGO 'Cheque';
GO

USE KOALASA
Go
EXEC SP_INGRESAR_PERSONA '123456789', 'Laura', 'Hernández', 'González', 'laurahernandez@email.com', '+506 78901234','Santa Lucia','V';
GO
EXEC SP_INGRESAR_PERSONA '1-11-12345', 'Carlos', 'Ruiz', 'Gutiérrez', 'carlosruiz@email.com', '+506 67890123','San Martin', 'C';
GO
EXEC SP_INGRESAR_PERSONA '5-442-813', 'Daniel', 'Díaz', 'Pérez', 'danieldiaz@email.com', '+506 89012345','Nicoya' ,'C';
GO

USE KOALASA
GO
Execute SP_CATALO_DE_ZAPATOS
GO

USE KOALASA
GO
EXECUTE AS USER = 'Vendedor';
GO
EXEC SP_INGRESAR_ARTICULO_A_CARRITO '3-3-41', 5;
EXEC SP_INGRESAR_ARTICULO_A_CARRITO '1-1-41', 1;
EXEC SP_GENERAR_COMPRA '5-442-813','123456789',1
GO
REVERT;
GO

use KOALASA
GO
EXECUTE SP_Audit_Compra;
GO
-- Tipo
USE KOALASA
GO
EXECUTE AS USER = 'KOALAADMIN'
GO
EXEC SP_EDITAR_NOMBRE_TIPO 1, 'Sandalia'
GO
REVERT;
GO

-- Color
USE KOALASA
GO
EXECUTE AS USER = 'KOALAADMIN'
GO
EXEC SP_EDITAR_NOMBRE_COLOR 1, 'Rojo'
GO
REVERT;
GO

-- Zapato
USE KOALASA
GO
EXECUTE AS USER = 'KOALAADMIN'
GO
EXEC SP_EDITAR_PRECIO_ZAPATO '1-1-41', 49.99
execute SP_BUSCAR_ZAPATO_POR_CODIGO '1-1-41'
EXECUTE SP_Audit_Zapato;
GO
REVERT;
GO


-- Stock
USE KOALASA
GO
EXECUTE AS USER = 'KOALAADMIN'
GO
EXEC SP_EDITAR_EXISTENCIAS_STOCK '1-1-41', 100
GO
REVERT;
GO

-- Persona
USE KOALASA
GO
EXECUTE AS USER = 'KOALAADMIN'
GO
EXEC SP_EDITAR_NOMBRE_PERSONA '123456789', 'NuevoNombre'
EXEC SP_EDITAR_APELLIDOS_PERSONA '123456789', 'NuevoApellido1', 'NuevoApellido2'
EXEC SP_EDITAR_APELLIDOS_PERSONA '123456789', 'NuevoApellido1'
EXEC SP_EDITAR_CORREO_PERSONA '123456789', 'nuevo@correo.com'
EXEC SP_EDITAR_TELEFONO_PERSONA '123456789', '8888-8888'
EXEC SP_EDITAR_TIPO_PERSONA '123456789', 'V'
GO
REVERT;
GO

-- Compra
USE KOALASA
GO
EXECUTE AS USER = 'KOALAADMIN'
GO
EXEC SP_EDITAR_METODO_PAGO_COMPRA 2, 2
GO
REVERT;
GO

-- Carrito_Compra
USE KOALASA
GO
EXECUTE AS USER = 'KOALAADMIN'
GO
EXEC SP_EDITAR_CANTIDAD_CARRITO 1, 5
GO
REVERT;
GO

--Eliminar Articulo del carrito
-- Carrito_Compra
USE KOALASA
GO
EXECUTE AS USER = 'KOALAADMIN'
GO
Execute SP_CATALO_DE_ZAPATOS
EXEC SP_DELETE_Articulo_Carrito 5
Execute SP_CATALO_DE_ZAPATOS
EXECUTE SP_Audit_Carrito;
GO
REVERT;
GO


