USE KOALASA
GO
Drop Procedure IF EXISTS SP_INGRESAR_PROVEEDOR
Drop Procedure IF EXISTS SP_INGRESAR_COLOR
Drop Procedure IF EXISTS SP_INGRESAR_TIPO
Drop Procedure IF EXISTS SP_INGRESAR_ZAPATO
Drop Procedure IF EXISTS SP_INGRESAR_STOCK
Drop Procedure IF EXISTS SP_INGRESAR_ARTICULO_A_CARRITO
Drop Procedure IF EXISTS SP_GENERAR_COMPRA
Drop Procedure IF EXISTS SP_AñADIR_METODO_PAGO
Drop Procedure IF EXISTS SP_INGRESAR_PERSONA

-- Update

USE KOALASA
GO

DROP PROCEDURE IF EXISTS SP_EDITARTELEFONO_PROVEEDOR;
DROP PROCEDURE IF EXISTS SP_EDITARCORREO_PROVEEDOR;
DROP PROCEDURE IF EXISTS SP_EDITARNOMBRE_PROVEEDOR;
DROP PROCEDURE IF EXISTS SP_BAJA_PROVEEDOR;
DROP PROCEDURE IF EXISTS SP_REACTIVAR_PROVEEDOR;
DROP PROCEDURE IF EXISTS SP_EDITAR_NOMBRE_TIPO;
DROP PROCEDURE IF EXISTS SP_EDITAR_PROVEEDOR_TIPO;
DROP PROCEDURE IF EXISTS SP_EDITAR_NOMBRE_COLOR;
DROP PROCEDURE IF EXISTS SP_EDITAR_TIPO_ZAPATO;
DROP PROCEDURE IF EXISTS SP_EDITAR_COLOR_ZAPATO;
DROP PROCEDURE IF EXISTS SP_EDITAR_TALLA_ZAPATO;
DROP PROCEDURE IF EXISTS SP_EDITAR_PRECIO_ZAPATO;
DROP PROCEDURE IF EXISTS SP_EDITAR_EXISTENCIAS_STOCK;
DROP PROCEDURE IF EXISTS SP_EDITAR_NOMBRE_PERSONA;
DROP PROCEDURE IF EXISTS SP_EDITAR_APELLIDOS_PERSONA;
DROP PROCEDURE IF EXISTS SP_EDITAR_CORREO_PERSONA;
DROP PROCEDURE IF EXISTS SP_EDITAR_TELEFONO_PERSONA;
DROP PROCEDURE IF EXISTS SP_EDITAR_TIPO_PERSONA;
DROP PROCEDURE IF EXISTS SP_EDITAR_NOMBRE_METODO_PAGO;
DROP PROCEDURE IF EXISTS SP_EDITAR_FECHA_COMPRA;
DROP PROCEDURE IF EXISTS SP_EDITAR_TOTAL_COMPRA;
DROP PROCEDURE IF EXISTS SP_EDITAR_CLIENTE_COMPRA;
DROP PROCEDURE IF EXISTS SP_EDITAR_VENDEDOR_COMPRA;
DROP PROCEDURE IF EXISTS SP_EDITAR_METODO_PAGO_COMPRA;
DROP PROCEDURE IF EXISTS SP_EDITAR_CANTIDAD_CARRITO;
DROP PROCEDURE IF EXISTS SP_EDITAR_SUBTOTAL_CARRITO;